blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('category/<str:slug>/', views.category_post_list, name='category_post_list'),
    path('tag/<str:slug>/', views.tag_post_list, name='tag_post_list'),
    path('post/<str:slug>/edit/', views.post_edit, name='post_edit'),
    path('post/<str:slug>/', views.post_detail, name='post_detail'),
    path('profile-edit',views.profile_edit, name='profile_edit'),
    # path('sign-up/', views.userSignUpViews, name='sign-up'),
    path('profile/', views.profile_view, name='profile'),
    path('post-new/', views.post_new, name='post_new'),
    # path('logout/', views.logout_view, name='logout'),
    # path('login/', views.login_view, name='login'),
    path('', views.post_list, name='post_list'),
]

business/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.business,name='business'),
    # path('feedback/',views.feedback,name='feedback'),
    path('logout/',views.logout_view,name='logout'),
    path('setup_feedback_form_details/<str:form_type>/',views.setupformdetails,name='setup_feedback_form_details'),
    path('addform/',views.addform,name='addform'),
    path('setup_feedback_form/',views.setupform,name='setup_feedback_form'),
    path('sign-up/', views.userSignUpViews, name='sign-up'),
    path('login/', views.login_view, name='login'),
    path('send-email/', views.send_email, name='send_email'),
    # path('customer_feedback/', views.customer_feedback, name='customer_feedback'),
    # path('customer_feedback/business/<int:business_id>/form/<int:form_id>/', views.customer_feedback, name='customer_feedback'),
    path('customer_feedback/business/<int:business_id>/form/<int:form_id>/<str:form_type>/', views.customer_feedback, name='customer_feedback'),
    path('business/download_feedbacks/', views.download_feedbacks_csv, name='download_feedbacks_csv'),
    path('team/',views.team,name='team'),
    # path('add-team-member/', views.add_team_member, name='add_team_member'),
    # path('delete-team-member/<int:member_id>/', views.delete_team_member, name='delete_team_member'),
    path('create-password/<str:uidb64>/<str:token>/', views.create_password, name='create_password'),
    # path('update-team-member/<int:member_id>/', views.update_team_member, name='update_team_member'),
    path('team/member/', views.manage_team_member, name='add_team_member'),  # View for adding a team member
    path('team/member/<int:member_id>/', views.manage_team_member, name='manage_team_member'),  # View for updating or deleting a team member
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('business.urls')),
    path("polls/", include('polls.urls')),
    path('blog/', include('blog.urls')),
    path('api/', include('blog.apiurls')),
    path('apibusiness/', include('business.apiurls')),
   
]                      
 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django_extensions.db.fields import AutoSlugField

STATUS_CHOICES = (
    ('Active', 'Active'),
    ('Inactive','Inactive'),
)

ROLE_CHOICES =(
    ('Owner','Owner'),
    ('Member','Member'),
)

class User(AbstractUser):
    phone_number = models.IntegerField(null=True, blank=True)
    email = models.EmailField(unique=True)
    city = models.CharField(max_length=250, null=True, blank=True)
    state = models.CharField(max_length=250, null=True, blank=True)
    country = models.CharField(max_length=250, null=True, blank=True)
    user_profile_image = models.ImageField(upload_to='user', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Inactive')
    Role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='Member')
    password = models.CharField(max_length=255)
    password_confirm = models.CharField(max_length=255)
    business_name = models.CharField(max_length=255)

    def __str__(self):
        return self.username


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='name')
    timestamp=models.DateTimeField(auto_now_add=True, editable=False)
    utimestamp=models.DateTimeField(auto_now=True, editable=False)
    track=models.TextField(blank=True)
    utrack=models.TextField(blank=True)
    status=models.CharField(max_length=10, choices=STATUS_CHOICES, default='Inactive')

    def __str__(self):
        return self.name
    
    
class Tag(models.Model):
    name = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from='name')
    timestamp=models.DateTimeField(auto_now_add=True, editable=False)
    utimestamp=models.DateTimeField(auto_now=True, editable=False)
    track=models.TextField(blank=True)
    utrack=models.TextField(blank=True)
    status=models.CharField(max_length=10, choices=STATUS_CHOICES, default='Inactive')


    def __str__(self):
        return self.name 
    

class Post(models.Model):
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    slug = AutoSlugField(populate_from='title')
    timestamp=models.DateTimeField(auto_now_add=True, editable=False)
    utimestamp=models.DateTimeField(auto_now=True, editable=False)
    feature_image = models.ImageField(upload_to='post/feature_image')
    thumbnail_image = models.ImageField(upload_to='post/thumbnail_image')
    published_date = models.DateTimeField()
    track=models.TextField(blank=True)
    utrack=models.TextField(blank=True)
    status=models.CharField(max_length=10, choices=STATUS_CHOICES, default='Inactive')

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments",on_delete=models.CASCADE)
    parent = models.ForeignKey('self', related_name="replies", on_delete=models.CASCADE,null=True, blank=True)
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField(unique=False, null=True, blank=True)
    text = models.TextField()
    timestamp=models.DateTimeField(auto_now_add=True, editable=False)
    utimestamp=models.DateTimeField(auto_now=True, editable=False)
    track=models.TextField(blank=True)
    utrack=models.TextField(blank=True)
    status=models.CharField(max_length=10, choices=STATUS_CHOICES, default='Inactive')

    def __str__(self):
        return  self.text
       

        
    

business/models.py
from django.db import models
from blog.models import User

STATUS_CHOICES = (
    ('Active', 'Active'),
    ('Inactive','Inactive'),
)
    
class Business(models.Model):
    teamMember = models.ManyToManyField(User)
    name = models.CharField(max_length=255)
    city = models.CharField(max_length=250, null=True, blank=True)
    state = models.CharField(max_length=250, null=True, blank=True)
    country = models.CharField(max_length=250, null=True, blank=True)
    logo = models.ImageField(upload_to='logo')
    created_at=models.DateTimeField(auto_now_add=True, editable=False)
    updated_at=models.DateTimeField(auto_now=True, editable=False)
    status=models.CharField(max_length=10, choices=STATUS_CHOICES, default='Inactive')

    def __str__(self):
        return self.name 
    
    
class FeedbackForm(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    status=models.CharField(max_length=10, choices=STATUS_CHOICES, default='Active')

    def __str__(self):
        return self.name
    
class Feedback(models.Model):
    business = models.ForeignKey(Business,on_delete=models.CASCADE)
    form_type = models.ForeignKey(FeedbackForm,on_delete=models.CASCADE, null=True, blank=True)
    text = models.TextField()
    rating = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    phone_number = models.IntegerField(null=True, blank=True)
    created_at=models.DateTimeField(auto_now_add=True, editable=False)
    updated_at=models.DateTimeField(auto_now=True, editable=False)
    status=models.CharField(max_length=10, choices=STATUS_CHOICES, default='Active')

    def __str__(self):
        return self.name 
    
class TextQuestions(models.Model):
    form_type = models.ForeignKey(FeedbackForm,related_name='text_questions',on_delete=models.CASCADE)
    text = models.TextField()
    created_at=models.DateTimeField(auto_now_add=True, editable=False)
    updated_at=models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.text 

class RateQuestions(models.Model):
    form_type = models.ForeignKey(FeedbackForm,related_name='rating_questions',on_delete=models.CASCADE)
    rating = models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True, editable=False)
    updated_at=models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.rating

business/forms.py
from django import forms
from .models import User

class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username',
            'phone_number',
            'city',
            'state',
            'country',
            'user_profile_image',
            'business_name'
        ) 
        exclude = ('password',)


class UserSignUpForm(forms.ModelForm):
    username = forms.CharField(
        required=False,  # Make the username field optional
        widget=forms.TextInput(attrs={'placeholder': 'Username'}),
    )
    password=forms.CharField(widget=forms.PasswordInput())
    confirm_password=forms.CharField(widget=forms.PasswordInput())
        
    class Meta:
        model = User
        fields = ('username', 'password','confirm_password','phone_number','email','city','state','country','business_name','user_profile_image')

    def clean(self):
        cleaned_data = super(UserSignUpForm, self).clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password != confirm_password:
            raise forms.ValidationError(
                "password and confirm_password does not match"
            )

class userloginForm(forms.ModelForm):
    username = forms.CharField(
    required=False,  # Make the username field optional
    widget=forms.TextInput(attrs={'placeholder': 'Username'}),)
    password=forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ('username', 'password')

business/templates/business.html
{% extends 'business_base.html' %}
{% load static %}
{% block content %}

{% if request.user.is_authenticated %}

<div style="display: grid; gap: 20px;">
<!-- <div class="review-container"> 
  <div class="review-header">
      <div class="review-rating">
          <b>Feedbacks</b> <span class="stars">★<span style="color: #555; font-size:15px;"> 4.4</span></span>
          <span class="results">(100 Results)</span>
      </div> -->
      <!-- <div class="filter-tags">
          <span>FarmAll Tags</span>
          <span>Dining</span>
      </div> -->
  <!-- </div> -->

  <!-- <div class="review-card"> -->
      <!-- <div class="review-info">
          <div class="review-title">
              <h4>The Game Palacio (Noida)</h4>
              <span class="review-date">Thu, Oct 3, 2024 10:33 AM</span>
          </div>
          <div class="rating-stars">
              <i class="fas fa-star star"></i>
              <i class="fas fa-star star"></i>
              <i class="fas fa-star star"></i>
              <i class="fas fa-star-half-alt star"></i>
              <i class="far fa-star star"></i>
          </div>
      </div> -->

      <!-- <div class="review-content">
          <div class="review-user" style="display: flex">
            <img src="./../static/css/images/no profile.jpeg" style="height: 35px; width: 35px;" />
            <div style="display: flex; flex-direction: column;" >
              <div style="display:flex; gap: 20px;">
              <span class="user-name">Pallav choudhary</span>
              <div style="border: 1px solid rgb(38, 223, 21);
              background-color: rgb(229, 240, 215);
              border-radius: 20px;
              padding-inline: 15px;
          ">
              <span style="color: rgb(38, 223, 21);" class="fa fa-star"></span>
              <span style="color: rgb(38, 223, 21);" class="fa fa-star checked"></span>
              <span style="color: rgb(38, 223, 21);"class="fa fa-star checked"></span>
              <span style="color: rgb(38, 223, 21);" class="fa fa-star"></span>
              <span style="color: rgb(38, 223, 21);" class="fa fa-star"></span>
            </div>
            </div>
              <span class="review-meta">
                <span class="add-phone" style="color: deeppink;"><i class="fa-solid fa-arrow-up-wide-short" ></i></span><span style="color: black;"> Add Order id</span> |
                <span class="order-id" style="color: deeppink;"><i class="fa-regular fa-envelope"></i></span><span style="color: black;"> Add Email</span> |
                <span class="add-time" style="color: deeppink;"><i class="fa-solid fa-phone"></i></span><span style="color: black;"> Add Phone</span> 
              </span>
            </div>
          </div><br>
       
          <div class="review-text">
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem perspiciatis qui aliquam sequi unde exercitationem veniam dolorum necessitatibus. Nulla unde impedit cumque voluptates ab, deleniti sapiente laudantium quasi reiciendis. Eum? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora deleniti alias omnis pariatur labore cupiditate, recusandae modi doloremque corrupti.</p>
          </div>
        </div>
        <div style="margin-top: 10px;">
        <p style="font-weight: 600; font-size: 11px;color: gray;">sat,oct 5,2024 5:04</p>
        </div> -->
       
      <!-- <div class="review-footer">
          <div class="response-status">
              <span>Not responded</span>
          </div>
          <div class="response-actions">
              <span>Dining</span>
          </div>
      </div> -->
  <!-- </div>
</div> -->

<div class="review-container">
  <div class="review-header">
      <div class="review-rating">
          <b>Feedbacks</b>
          <span class="stars">
              {% for _ in avg_rating_range %}★{% endfor %}
              {% for _ in avg_rating_empty_range %}☆{% endfor %}
              <span style="color: black;">{{ avg_rating }}</span>
          </span>
          <span class="results">({{ feedbacks|length }} Results)</span>
        </div>
        <!-- <button class="btn" style="background-color: #eb308e; display: flex; gap: 5px; align-items: center;"><i class="fa-solid fa-download"></i>Export</button> -->
        <button class="btn" style="background-color: #eb308e">
          <a href="{% url 'download_feedbacks_csv' %}" style="color: white; text-decoration: none; display: flex;gap: 5px; align-items: center;">
              <i class="fa-solid fa-download"></i>Export
          </a>
      </button>
</div>
</div>
  {% for feedback in feedbacks %}
<div class="review-container">

  <div class="review-card"  >
      <div class="review-content" style="display: flex; justify-content: space-between;">
          <div class="review-user" style="display: flex">
            <img src="./../static/css/images/no profile.jpeg" style="height: 35px; width: 35px;" />
              <div style="display: flex; flex-direction: column;">
                  <!-- <div style="display:flex; gap: 20px;margin-top: 0%;"> -->
                    <div style="display:flex; gap: 20px;">
                      <span class="user-name">{{ feedback.name }}</span>
                      <!-- <span class="user-name"><i class="fa-solid fa-user fa-2xl" style="color: gray; "></i>  <span style="margin-top: 20px;font-size: larger;"></span> {{ feedbacks.name }}</span> -->
                      <div style="border: 1px solid rgb(38, 223, 21); background-color: rgb(229, 240, 215); border-radius: 20px; padding-inline: 15px; color: rgb(38, 223, 21);">
                          {% for _ in feedback.star_range %}★{% endfor %}
                          {% for _ in feedback.empty_star_range %}☆{% endfor %}
                      </div>
                  </div>
                  <span class="review-meta">
                      <span style="color: grey;" class="order-id"> <i class="fa-regular fa-envelope" style="color: deeppink;"></i> {{ feedback.email }} |</span>
                      <span style="color: grey;" class="add-time"> <i class="fa-solid fa-phone" style="color: deeppink;"></i>  {{ feedback.phone_number }}</span>
                  </span>
              </div>
            
            </div>
            <p>{{ feedback.form_type }}</p>
          </div>
          <div class="review-text">
             <p style="font-size: small;margin-bottom: 0px;"> <strong>Feedback:</strong> {{ feedback.text|linebreaksbr }}</p>
              <br>
              <p style="font-size: small;margin-bottom: 0px;"><strong>Rating Details:</strong> {{ feedback.rating|linebreaksbr  }}</p>
          </div>
      </div>
      <div style="margin-top: 12px;">
          <p style="color: grey;font-size: small; margin-left: 15px;">{{ feedback.created_at|date:"D, M d, Y H:i" }}</p>
      </div>
      </div>
  {% empty %}
  <p>No feedbacks available yet.</p>
  {% endfor %}
</div>

{% endif %}
{% endblock %}

business/templates/business_base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <a href="https://en.wikipedia.org/wiki/Django" class="external_link" id="link_to_wiki_page"></a>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext">
        <link rel="stylesheet" type="text/css" href="{% static './css/business.css' %}"/>
        <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOM7F4s+M/A7NwzB/2xQn8F7d+4eF1k3fo9kplJ" crossorigin="anonymous"> -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
        <link rel="shortcut icon" href="http://MY-CDN.example.com/favicon.ico" />
        <link rel="stylesheet" type="text/css" href="{% static './css/business.css' %}"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">


        <!-- {% block style %} -->
        <!-- {% endblock %} -->
         {% block tittle %} {% endblock %}
         {% block meta %}{% endblock %}
         <style>
        
            
            .dark-mode {
              background-color: black;
              color: #086891;
            }
            </style>
    </head>
    <body>
         {% include './header.html' %}
    <main class="container">
        <div class="row">
            <div class="col">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </main>
    <script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>

    <script>
        function myFunction() {
           var element = document.body;
           element.classList.toggle("dark-mode");
        }
        </script>
        
    </body>
</html>

business/templates/header.html
{% load static %}
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
  crossorigin="anonymous"
/>
<link
  rel="stylesheet"
  type="text/css"
  href="{% static './css/business.css' %}"
/>

{% if request.user.is_authenticated %}

<div
  style="
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    padding: 40px;
  "
>
  <ul
    class="nav nav-pills"
    style="
      border: 1px solid black;
      border-radius: 8px;
      background-color: #f3f3f3;
    "
  >
    <li class="nav-item" style="border-right: 1px solid; padding: 2px">
      <a
        class="nav-link {% if request.path == '/' %}feedbackActiveTab{% endif %}"
        aria-current="page"
        style="color: black"
        href="{% url 'business' %}"
        >Feedback</a  
      >
    </li>
    <li class="nav-item" style="border-right: 1px solid; padding: 2px">
      <a
        class="nav-link {% if request.path == '/team/' %}feedbackActiveTab{% endif %}"
        style="color: black"
        href="{% url 'team' %}"
        >Team</a
      >
    </li>
    <li class="nav-item" style="padding: 2px">
      <a
        class="nav-link {% if request.path == '/setup_feedback_form/' %}feedbackActiveTab{% endif %}"
        style="color: black"
        href="{% url 'setup_feedback_form' %}"
        >Setup Feedback Form</a
      >
    </li>
  </ul>

  <ol style="padding: 0px; margin: 0px">
    <div>
      <div
        style="
          margin-right: 20px;
          display: flex;
          align-items: center;
          justify-content: end;
          gap: 5px;
        "
      >
<i class="fa-solid fa-circle-half-stroke"  onclick="myFunction()" style="cursor: pointer;"></i>

        {% for business in businesses %} {% if business.logo %}
        <img
          src="{{ business.logo.url }}"
          alt="Business Logo"
          style="width: 50px; height: 50px; border-radius: 50%"
        />
        {% endif %}
        <strong>user</strong>
        <div class="dropdown">
          <i
            class="fa-solid fa-caret-down"
            type="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
          </i>
          <ul class="dropdown-menu">
            <div style="display: flex">
              <div>
                <img
                  src="{{ business.logo.url }}"
                  alt="Business Logo"
                  style="
                    width: 50px;
                    height: 50px;
                    border-radius: 50%;
                    margin-left: 10px;
                    margin-top: 5px;
                  "
                />
              </div>
              <div>
                <li>
                  <a
                    style="color: rgb(250, 96, 6)"
                    class="dropdown-item"
                    href="#"
                    ><b>{{ user.username }}</b></a
                  >
                </li>
                <li><a class="dropdown-item" href="#">{{ user.email }}</a></li>
              </div>
            </div>
            <hr />
            <li>
              <a
                class="dropdown-item"
                data-bs-toggle="modal"
                data-bs-target="#exampleModal"
                style="cursor: pointer"
              >
                <i class="fa-solid fa-user" style="color: #080808"></i
                >&nbsp;&nbsp;&nbsp; Settings
              </a>
            </li>
            <hr />
            <li>
              <a class="dropdown-item" href="{% url 'logout' %}">
                <i
                  class="fa-solid fa-arrow-right-from-bracket fa-rotate-180"
                  style="color: #0c0d0d; margin-top: 0%"
                ></i
                >&nbsp;&nbsp;&nbsp;logout
              </a>
            </li>
          </ul>
        </div>
      </div>
      <br />
    </div>

    <button
      type="button"
      class="btn btn-primary"
      data-bs-toggle="modal"
      id="modelForm"
      data-bs-target="#exampleModal"
    ></button>

    <div
      class="modal fade"
      id="exampleModal"
      tabindex="-1"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1
              class="modal-title fs-5"
              id="exampleModalLabel"
              style="font-family: Arial, Helvetica, sans-serif"
            >
              Settings
            </h1>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <div>
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="edit-profile" style="padding: 15px;display: flex;flex-direction: column;gap: 20px;">
                <div>
                  <h3 style="margin-bottom: 0; font-family: none;">Phone Number</h3>
                  <input
                    type="text"
                    name="phone_number"
                    value="{{ user.phone_number }}"
                    maxlength="30"
                    id="id_phone_number"
                  />
                </div>
                <div>
                  <h3 style="margin-bottom: 0; font-family: none;">Username</h3>
                  <input
                    type="text"
                    name="username"
                    value="{{ user.username }}"
                    maxlength="150"
                    required=""
                    id="id_username"
                  />
                </div>
                <div>
                  <h3 style="margin-bottom: 0; font-family: none;">City</h3>
                  <input
                    type="text"
                    name="city"
                    value="{{ user.city }}"
                    maxlength="400"
                    id="id_city"
                  />
                </div>
                <div>
                  <h3 style="margin-bottom: 0; font-family: none;">Email</h3>
                  <input
                    type="email"
                    name="email"
                    value="{{ user.email }}"
                    maxlength="254"
                    id="id_email"
                  />
                </div>
                <div>
                  <h3 style="margin-bottom: 0; font-family: none;">State</h3>
                  <input
                    type="text"
                    name="state"
                    value="{{ user.state }}"
                    maxlength="254"
                    id="id_state"
                  />
                </div>
                <div>
                  <h3 style="margin-bottom: 0; font-family: none;">Country</h3>
                  <input
                    type="text"
                    name="country"
                    value="{{ user.country }}"
                    maxlength="254"
                    id="id_country"
                  />
                </div>
                <div>
                  <h3 style="margin-bottom: 0; font-family: none;">Profile Image</h3>
                  <input type="file" name="image" id="id_user_profile_image" />
                </div>
                <div>
                  <h3 style="margin-bottom: 0; font-family: none;">Business Name</h3>
                  <input
                    type="text"
                    name="business_name"
                    value="{{ user.business_name }}"
                    maxlength="254"
                    id="id_business_name"
                  />
                </div>
              </div>
              <div>
                <div class="modal-footer" style="display: flex; justify-content: space-between;">
                  <button
                    type="button"
                    class="btn btn-secondary"
                    data-bs-dismiss="modal"
                  >
                    Close
                  </button>
                  <button
                    type="submit"
                    class="btn"
                    style="background-color: #eb308e"
                  >
                    Save changes
                  </button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    {% endfor %} {% else %}
    <!-- <a style="text-decoration: none; color: black" href="{% url 'sign-up' %}"
      >&nbsp;<b>Sign Up</b>
    </a>
    <a style="text-decoration: none; color: black" href="{% url 'login' %}"
      >&nbsp;<b>Login</b>
    </a> -->
    {% endif %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
      integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <script>
      $(document).ready(function () {
        $("#modelForm").hide();
      });
    </script>
  </ol>
</div>